<a href="https://colab.research.google.com/github/Koar-create/Yang-Repository-CS/blob/main/pre-course/%5BExercise%5D_Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **[Exercise] Numpy tasks.ipynb**

Author: Zhixian Yang

Email: yangzhx28@mail2.sysu.edu.cn

GitHub: https://github.com/koar-create

Date created: July 14th, 2023

Last modified: July 14th, 2023

<br><br>

---

<br><br>

## **Description**
This document is a Jupyter Notebook designed for an exercise derived from the "Computational Tools for Climate Science 2023" course offered by Climatematch Academy. The code presented here comprises a combination of materials provided in the course and code obtained from online sources.

In [ ]:
import numpy as np

# **Task 1:**

---
**Description:** Please, write a function that finds the sum of the even diagonal elements of a square matrix if there are no such elements, output 0.

In [ ]:
def diagonal_square_matrix_sum(a):
  return sum([i for i in a.diagonal() if (i % 2) == 0])

a = np.random.randint(1, 10, size=(10,10))
print(a)
sum = diagonal_square_matrix_sum(a)
print(sum)

[[9 6 4 3 2 7 6 9 8 8]
 [6 7 2 9 7 6 7 7 7 7]
 [8 4 2 8 1 9 3 5 7 3]
 [1 6 5 9 6 8 7 8 1 5]
 [3 8 1 2 9 8 7 2 7 4]
 [4 7 6 7 8 1 4 5 5 8]
 [2 9 9 3 9 7 2 9 1 3]
 [2 4 8 6 3 4 1 1 3 9]
 [1 8 5 3 6 9 7 9 7 3]
 [6 7 6 8 3 1 4 5 9 1]]
4


# **Task 2:**

---
**Description:** You have two dimensional array X. For every line in array X you must do the following transformation.

You have a line x. You need to create a new array where all the elements with an odd indices will be replaced with the number a. All elements with odd indices should be cubed. Then you write elements in reverse relative to their positions.  Then you need to merge transformed array with the given array and return it. The original X should not be transformed!

In [ ]:
from copy import copy

def transform(X, a=1):
  Y = np.copy(X)
  Y[:, 1::2] = a
  Y[:, ::2]  = Y[:, ::2] ** 3
  return np.concatenate([X, Y[:, ::-1]], axis=0)

X = np.array([[100,200,300,400,500, 600], [200, 300, 500, 22, 11, 17]])
transform(X)

array([[      100,       200,       300,       400,       500,       600],
       [      200,       300,       500,        22,        11,        17],
       [        1, 125000000,         1,  27000000,         1,   1000000],
       [        1,      1331,         1, 125000000,         1,   8000000]])